// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/signalwatch-globe/Current.tsx": () => import("../components/mockups/signalwatch-globe/Current.tsx"),
  "./components/mockups/signalwatch-globe/InteractiveSectorGlobe.tsx": () => import("../components/mockups/signalwatch-globe/InteractiveSectorGlobe.tsx"),
  "./components/mockups/signalwatch-globe/SatelliteGlobe.tsx": () => import("../components/mockups/signalwatch-globe/SatelliteGlobe.tsx"),
  "./components/mockups/signalwatch-refined/FieldDesk.tsx": () => import("../components/mockups/signalwatch-refined/FieldDesk.tsx")
};
